### ISSUE TITLE
sublime4好像失效了

### ISSUE THREAD

**Issue by Ustuode** [floydawong/LuaFormat#27]
sublime4好像失效了 快捷键用了没反应

**Comment by floydawong** [comment]
这是一个入门级的格式化插件, 只能处理一些"规范"的Lua代码.  
推荐使用: https://github.com/floyda-sublime/sublime-lua-format fork from: https://github.com/Koihik/sublime-lua-format

关于ST4快捷键冲突的问题, 你可以尝试一下改成其他快捷键.

**Comment by AlixesGit** [comment]
虽然大佬很谦虚 但这两个 format 都用过
还是您这用起来更舒服

推荐使用: 的 这个插件一直有一些问题 比如格式化以后会出现很多 <0x087> 类似这样的代码...(具体内容可能不是这个就记住了<0x...>)

而您的作品完全没有这个问题 除了有一个略微头痛的小bug
就是有时候 有的参数如果是类似下面这样
local  foo = 'asd' .. 'sdf%s dfs' .. bar .. string.format(STR, ' %d') ...
格式化后会变成 
local  foo = 'asd ' .. 'sdf %s  dfs' .. bar .. string.format(STR, '   % d ') ...(多了一些空格)
不知道什么原因


PS 这次st4 似乎是不兼容问题不是快捷键冲突 暂时只好同时保留 st3 和st4 需要格式化的时候开3格式一下 
希望大佬有空时候 可以更新一下

**Comment by AlixesGit** [comment]
问题可能出在17行的版本兼容性上 不知道是不是这样

**Comment by AlixesGit** [comment]
os.date('%Y%m%d %H%M') 也会变成 os.date( ' %  Y % m % d   % H % M ' )

**Comment by Ustuode** [comment]
> 虽然大佬很谦虚 但这两个 format 都用过
> 还是您这用起来更舒服
> 
> 推荐使用: 的 这个插件一直有一些问题 比如格式化以后会出现很多 <0x087> 类似这样的代码...(具体内容可能不是这个就记住了<0x...>)
> 
> 而您的作品完全没有这个问题 除了有一个略微头痛的小bug
> 就是有时候 有的参数如果是类似下面这样
> local foo = 'asd' .. 'sdf%s dfs' .. bar .. string.format(STR, ' %d') ...
> 格式化后会变成
> local foo = 'asd ' .. 'sdf %s dfs' .. bar .. string.format(STR, ' % d ') ...(多了一些空格)
> 不知道什么原因
> 
> PS 这次st4 似乎是不兼容问题不是快捷键冲突 暂时只好同时保留 st3 和st4 需要格式化的时候开3格式一下
> 希望大佬有空时候 可以更新一下

说的很彻底

**Comment by floydawong** [comment]
```
if sublime.version().startswith('3'):
    from .core import *
else:
    from core import *
```

写插件的时候, 根本没想到Sublime版本号为4开头的情况.  

就像我在写这个插件的时候, 根本就没考虑闭包做变量或者参数的情况    

觉得市面上没有Lua的格式化工具, 就卷起袖子开始撸了. 完全是按自己对Lua的理解, 和平时自己的一些习惯来写的.   

所以, 这个插件对于我个人来说, 是完全OK的, 你们说的那些Bug, 不是我的问题, 是我根本想不到可以这样写 ^_^&

--- 

那我再推荐一个吧 : LSP(Sublime) + LSP-Lua(VSCode), 用VSCode的插件, 来格式化Sublime打开的文件. 
这个还是有一些小的Bug, 不过已经很完善了.

---

最后, 感谢各位的支持和肯定, 这个插件开始的设计就有问题, 除非重写一个, 不然上限就这样了...
